### ISSUE TITLE
[warning ]Unexpected input(s) 'postmanApiKey'

### ISSUE THREAD

**Issue by patrickwyler** [matt-ball/newman-action#11]
The action will generate a warning like the following one:

`##[warning]Unexpected input(s) 'postmanApiKey', valid inputs are ['apiKey', 'collection', 'environment', 'globals', 'iterationCount', 'iterationData', 'folder', 'workingDir', 'insecureFileRead', 'timeout', 'timeoutRequest', 'timeoutScript', 'delayRequest', 'ignoreRedirects', 'insecure', 'bail', 'suppressExitCode', 'reporters', 'reporter', 'color', 'sslClientCert', 'sslClientKey', 'sslClientPassphrase']`

![image](https://user-images.githubusercontent.com/23375188/91698368-e04a8280-eb72-11ea-86a3-09d9dd71e46b.png)

Wouldn't it be better to use the _apiKey_ param directly instead of the _postmanApiKey_ which will be passed to the apiKey anyway? 

Could be related to this [Pull Request](https://github.com/matt-ball/newman-action/pull/5)

**Comment by matt-ball** [comment]
Should be OK in latest release
