### ISSUE TITLE
Latest releases broke our existing tests, had to revert to 0.0.28

### ISSUE THREAD

**Issue by rik2803** [matt-ball/newman-action#14]
FYI.

Our integration tests used to specify `matt-ball/newman-action@master`, but the tests started to fail yesterday, no changes were made to the test collections. I noticed the new releases and assumed that was the cause of the failures.

Specifying `0.0.28` instead made the tests pass again.

**Comment by matt-ball** [comment]
Thanks for reporting @rik2803 do you have any specifics or a repo you can share?

**Comment by niklasmattsson** [comment]
I see the same problem with our tests, but it does not help using 0.0.28 in my case.

I noticed that it does not print out  
apiKey: postmanApiKey ... suppressExitCode: false anymore. The only field presented is reporters: cli.

**Comment by matt-ball** [comment]
@niklasmattsson do you have a link to the repo where this is happening or some more details logs/screenshots you can share? The information you've provided isn't much to go off.

**Comment by rik2803** [comment]
What exactly do you require? The collection is there and the logs. Only the environment file is missing.

**Comment by AustinTamb** [comment]
Our project tests started failing as well. Here's the type of issue we're having:

`01.  AssertionError  Validating request status...                                        
                      expected { Object (id, _details, ...) } to have property 'code'     
                      at assertion:0 in test-script                                       
                      inside "No Auth Required / Permissions"                             
                                                                                          
 02.  AssertionError  Validating request status...                                        
                      expected { Object (id, _details, ...) } to have property 'code'     
                      at assertion:0 in test-script                                       
                      inside "Setup / Login"                                              
                                                                                          
 03.  JSONError       Validating for successful login...                                  
                      Unexpected token u in JSON at position 0                            
                      at assertion:1 in test-script                                       
                      inside "Setup / Login"     `

On those lines, we use the `pm` object. Maybe the issue has to do with that? I really don't know the specifics of how this works, so I can't really suggest anything else.

**Comment by matt-ball** [comment]
You might try reverting to the earlier version, or running Newman standalone to see if the issue persists. The latest version of the action uses Newman v5, whereas 0.0.28 was using v4.

Happy to review one of those failing test scripts here if it is shareable. 

I've tested a number of collections on my side with the latest version and things pass - so if anyone has a collection to share, even with one req/failing script I can dig in that way too.

**Comment by niklasmattsson** [comment]
I specify the `globals` parameter to a file path.

I think the change `globals: safeParse(get('globals')),` will not make that possible anymore.

**Comment by matt-ball** [comment]
@niklasmattsson globals, or something else?

https://github.com/matt-ball/newman-action/blob/master/index.js#L17

**Comment by AustinTamb** [comment]
Here's the test script:
```
// Add a test to ensure that the status code we got is what we expected.
pm.test( "Validating request status...", () => 
    {
        // Validate the response code.
        pm.response.to.have.status(200);
    }
);

// Add a test for ensure the login was successful.
pm.test( "Validating for successful login...", () => 
    {
        // Parse the response.
        const response = pm.response.json();
        // Validate the login value.
        pm.expect(response.login).to.be.true;
    }
);

// Add the test for the new token.
pm.test( "Testing for refresh CSRF token...", () =>
    {
        // Ensure the refresh cookie is there.
        pm.expect(
            pm.cookies.has("csrf_refresh_token")
        ).to.be.true;

        // Get the value in the cookie.
        var refreshToken = postman.getResponseCookie("csrf_refresh_token");
        // Ensure we get a different refresh token.
        pm.expect(pm.variables.get("csrfRefreshToken")).not.eq(refreshToken.value);

        // Update the token.
        pm.variables.set("csrfRefreshToken", refreshToken.value);
        // Ensure the environmental variable was updated.
        pm.expect(pm.variables.get("csrfRefreshToken")).to.equal(refreshToken.value);
    }
);
// Update the environmental variables.
pm.test( "Testing for access CSRF token...", () =>
    {
        // Ensure the access cookie is there.
        pm.expect(
            pm.cookies.has("csrf_access_token")
        ).to.be.true;

        // Get the value in the cookie.
        var accessToken = postman.getResponseCookie("csrf_access_token");
        // Ensure we get a different access token.
        pm.expect(pm.variables.get("csrfAccessToken")).not.eq(accessToken.value);

        // Update the token.
        pm.variables.set("csrfAccessToken", accessToken.value);
        // Ensure the environmental variable was updated.
        pm.expect(pm.variables.get("csrfAccessToken")).to.equal(accessToken.value);
    }
);
```
Here's the errors for that specific test script:
```
 02.  AssertionError  Validating request status...                                        
                      expected { Object (id, _details, ...) } to have property 'code'     
                      at assertion:0 in test-script                                       
                      inside "Setup / Login"                                              
                                                                                          
 03.  JSONError       Validating for successful login...                                  
                      Unexpected token u in JSON at position 0                            
                      at assertion:1 in test-script                                       
                      inside "Setup / Login"                                              
                                                                                          
 04.  AssertionError  Testing for refresh CSRF token...                                   
                      expected false to be true                                           
                      at assertion:2 in test-script                                       
                      inside "Setup / Login"                                              
                                                                                          
 05.  AssertionError  Testing for access CSRF token...                                    
                      expected false to be true                                           
                      at assertion:3 in test-script                                       
                      inside "Setup / Login"
```

This is just a typical login script. Our authentication is done through JWT cookies, specifically, using flask-jwt-extended ones. Pretty much, the last two tests are mainly done to extract the cookies needed for accessing protected endpoints later on. These work in the postman runner.

**Comment by niklasmattsson** [comment]
> @niklasmattsson globals, or something else?
> 
> https://github.com/matt-ball/newman-action/blob/master/index.js#L17

Sorry, my bad. I was looking at https://github.com/matt-ball/newman-action/pull/5/files

**Comment by matt-ball** [comment]
@AustinTamb curious. I copied your script and mocked up a request to make the script execute. I don't get any of the execution errors you've hit, other than an expected test failure:

https://github.com/matt-ball/users-api/runs/1423736389#step:6:9

Perhaps you could try running newman locally to see if you get the same result.

**Comment by ShaunEgan** [comment]
This broke our tests as well, reverting to 0.0.28 resolved our issue.

**Comment by matt-ball** [comment]
@ShaunEgan what errors are you seeing / do you have an excerpt of test script you can share? Thus far, I can only assume this is due to the switch to Newman v5 as I've successfully run some provided snippets (above) but would love to unblock you all/understand better.

**Comment by ffflabs** [comment]
@matt-ball perhaps you already ruled this one out, but I'd point at

https://github.com/matt-ball/newman-action/blob/fdeaa163e1a3d01d4ada53f9a1d25e9608474e68/index.js#L14

Which used to be, 

https://github.com/matt-ball/newman-action/blob/ddf114ede359e6f7fdbfaded6bd4f9861a41140d/index.js#L13

perhaps someone is still using the old parameter name?

**Comment by JanC** [comment]
hey,
I believe I have the same issue. I initially setup GH actions using npm  to install newmap and running using 

```yml
 - name: run tests
        run: newman run collections/mobile-app.postman_collection.json --environment environments/dev.postman_environment.json
```

this works well but when I switch to `matt-ball/newman-action@master` it fails:

```yml
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: collections/mobile-app.postman_collection.json
          environment: environments/dev.postman_environment.json
```


The failures are 
```
1.  JSONError                                               
                Unexpected token u in JSON at position 0     
                at test-script                               
                inside "My request"  
```

**Comment by cynicaljoy** [comment]
Same issue here, tests run/pass in Postman but failed with `master` version of the action, reverting to `0.0.28`  builds pass -- but the output doesn't show the Postman Newman run output so maybe tests just aren't running 🤷 

### Details from failed action run of `master`

#### Postman Tests

```
pm.test("Status code is 200", function () {
    pm.response.to.have.status(200);
});

pm.test("Message body returns as expected", function () {
    var jsonData = pm.response.json();
    pm.expect(jsonData.message).to.eql("Hello, World");
});

pm.test("Headers", function() {
   pm.response.to.have.header("Access-Control-Allow-Origin", "*");
   pm.response.to.have.header("Access-Control-Allow-Headers", "Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization");
});
```

#### Action output

```
  #  failure         detail                                                                  
                                                                                             
 1.  AssertionError  Status code is 200                                                      
                     expected { Object (id, _details, ...) } to have property 'code'         
                     at assertion:0 in test-script                                           
                     inside "hello / Say hello"                                              
                                                                                             
 2.  JSONError       Message body returns as expected                                        
                     Unexpected token u in JSON at position 0                                
                     at assertion:1 in test-script                                           
                     inside "hello / Say hello"                                              
                                                                                             
 3.  AssertionError  Headers                                                                 
                     expected response to have header with key 'Access-Control-Allow-Origin' 
                     at assertion:2 in test-script                                           
                     inside "hello / Say hello"    

```

**Comment by matt-ball** [comment]
Does anyone have a repo they can link or a complete collection that they can share? Unfortunately these test scripts on their own execute just fine for me.

**Comment by cynicaljoy** [comment]
I created a repo that I set up with a workflow that's linked to a new Workspace, Collection, with a Test Suite that I was able to recreate the issue with. I just invited you to collaborate.

**Comment by matt-ball** [comment]
It would be interesting to test that theory rather than completely change the project. Unfortunately, I can't access the repo you shared anymore. If it is down to `node_modules`, there are [other ways](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github) we can solve that.

**Comment by matt-ball** [comment]
All, please feel free to try v0.2.3 to see if it works for you.

**Comment by cynicaljoy** [comment]
Nope, v.0.2.3 still fails https://github.com/cynicaljoy/newman-action-sandbox/runs/1577300708

**Comment by cynicaljoy** [comment]
I wasn't trying to completely change the project but rather bring it back inline with the initial fork.

**Comment by Ryuichiro** [comment]
Will this be addressed in an "official" patch?

Regardless what I throw at the action, everything returns:
`Unexpected token u in JSON at position 0`
