### ISSUE TITLE
envVar is not working in Github action

### ISSUE THREAD

**Issue by ankaushik29** [matt-ball/newman-action#48]
Hi, 

I am using this github action and getting below error when i use envVar. I want to overwrite token variable which is already defined in a environment.json.
CODE:
 name: Run API Test Suite
        id: run-newman
        uses: matt-ball/newman-action@master
        with:
          collection: test/src/collection/cicd-testsuite.json
          environment: test/src/collection/LocalDev.postman_environment.json      
          reporters: cli
          delayRequest: 250
          envVar: '[{ "key": "Token", "value":"XYZ123@"}]'

Error: 
Warning: Bad object passed in config!
Error: Newman run failed! 

Thanks!!

**Comment by matt-ball** [comment]
`reporters` only supports stringified objects, see:
https://github.com/matt-ball/newman-action#other-settings

Since the default is for the CLI reporter anyway, can you remove that line from your config altogether and try again?

**Comment by ankaushik29** [comment]
It worked, Thanks for your support :)
