### ISSUE TITLE
Using reporter

### ISSUE THREAD

**Issue by shurik88** [matt-ball/newman-action#8]
I don't understand how to specify reporter options in yaml
for example:
how to use argument reporter : { junit : { export : './xmlResults.xml' } }
Please tell me

**Comment by arauchberger** [comment]
i have the same question - would be happy if somebody could explain.

i'm currently trying this

reporters: cli,junit,html,htmlextra
reporter: "{ junit: { export: './TEST-newman-report.xml' }, htmlextra: { export: './newman-report-extra.html' }}"
